import { useEffect, useState } from 'react';
import { useNavigate, useLocation, Link } from 'react-router-dom';
import { FileCheck, CheckCircle, AlertTriangle, XCircle, Download, Copy, Upload, AlertCircle } from 'lucide-react';
import { Button } from '../components/ui/Button';
import { Card } from '../components/ui/Card';
import { getVerdictBgColor, getVerdictBorderColor, getVerdictColor } from '../utils/mockApi';
import type { AnalysisResponse } from '../types';

export const ResultPage = () => {
  const [copied, setCopied] = useState(false);
  const navigate = useNavigate();
  const location = useLocation();
  const result = location.state?.result as AnalysisResponse | undefined;
  const fileName = location.state?.fileName as string | undefined;

  useEffect(() => {
    if (!result) {
      navigate('/upload');
    }
  }, [result, navigate]);

  if (!result) {
    return null;
  }

  const getVerdictIcon = () => {
    switch (result.verdict) {
      case 'Safe':
        return <CheckCircle className="w-12 h-12 text-green-600" />;
      case 'Medium Risk':
        return <AlertTriangle className="w-12 h-12 text-yellow-600" />;
      case 'Unsafe':
        return <XCircle className="w-12 h-12 text-red-600" />;
    }
  };

  const getRiskIcon = (text: string) => {
    if (text.includes('✓') || text.includes('✅')) {
      return <CheckCircle className="w-5 h-5 text-green-600 flex-shrink-0" />;
    } else if (text.includes('⚠') || text.toLowerCase().includes('medium')) {
      return <AlertTriangle className="w-5 h-5 text-yellow-600 flex-shrink-0" />;
    } else if (text.includes('✕') || text.includes('❌')) {
      return <XCircle className="w-5 h-5 text-red-600 flex-shrink-0" />;
    }
    return <AlertCircle className="w-5 h-5 text-gray-500 flex-shrink-0" />;
  };

  const handleCopy = async () => {
    const text = `
Agreement Analysis Report
File: ${fileName || 'Document'}
Verdict: ${result.verdict}
Risk Score: ${result.score}/100

Summary:
${result.summary.map((item, idx) => `${idx + 1}. ${item}`).join('\n')}

Recommendation:
${result.recommendation}

Disclaimer: This is not legal advice. For awareness only.
    `.trim();

    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  const handleDownload = () => {
    const text = `
Agreement Analysis Report
=======================

File: ${fileName || 'Document'}
Date: ${new Date().toLocaleDateString('en-IN')}

Verdict: ${result.verdict}
Risk Score: ${result.score}/100

Summary:
--------
${result.summary.map((item, idx) => `${idx + 1}. ${item}`).join('\n')}

Recommendation:
--------------
${result.recommendation}

Disclaimer:
-----------
This is not legal advice. This analysis is for informational purposes only.
For legal matters, please consult a qualified lawyer.

Generated by Agreement Checker AI
    `.trim();

    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${fileName?.replace(/\.[^/.]+$/, '') || 'document'}-analysis.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-blue-50 to-white">
      <nav className="bg-white shadow-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex items-center justify-between">
            <Link to="/" className="flex items-center space-x-2">
              <FileCheck className="w-8 h-8 text-blue-600" />
              <span className="text-xl font-bold text-gray-900">Agreement Checker AI</span>
            </Link>
            <Link to="/dashboard">
              <Button variant="ghost">My Documents</Button>
            </Link>
          </div>
        </div>
      </nav>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">Analysis Complete</h1>
          <p className="text-gray-600">
            {fileName && <span className="font-medium">{fileName}</span>}
          </p>
        </div>

        <Card className={`mb-6 border-2 ${getVerdictBorderColor(result.verdict)} ${getVerdictBgColor(result.verdict)}`}>
          <div className="flex items-center justify-between flex-wrap gap-4">
            <div className="flex items-center space-x-4">
              {getVerdictIcon()}
              <div>
                <h2 className={`text-2xl font-bold ${getVerdictColor(result.verdict)}`}>
                  {result.verdict}
                </h2>
                <p className="text-gray-700">Risk Score: {result.score}/100</p>
              </div>
            </div>
          </div>
        </Card>

        <Card className="mb-6">
          <h3 className="text-xl font-semibold text-gray-900 mb-4">
            Document Summary
          </h3>
          <ul className="space-y-3">
            {result.summary.map((item, index) => (
              <li key={index} className="flex items-start space-x-3">
                {getRiskIcon(item)}
                <span className="text-gray-700 flex-1">{item}</span>
              </li>
            ))}
          </ul>
        </Card>

        <Card className="mb-6 bg-blue-50 border-2 border-blue-200">
          <div className="flex items-start space-x-3">
            <AlertCircle className="w-6 h-6 text-blue-600 flex-shrink-0 mt-1" />
            <div>
              <h3 className="text-lg font-semibold text-gray-900 mb-2">
                Our Recommendation
              </h3>
              <p className="text-gray-700">{result.recommendation}</p>
            </div>
          </div>
        </Card>

        <Card className="mb-6 bg-yellow-50 border-2 border-yellow-300">
          <div className="flex items-start space-x-3">
            <AlertTriangle className="w-6 h-6 text-yellow-600 flex-shrink-0 mt-1" />
            <div>
              <h3 className="text-lg font-semibold text-gray-900 mb-2">
                Important Disclaimer
              </h3>
              <p className="text-gray-700">
                This analysis is for informational purposes only and does not constitute legal advice.
                Always consult a qualified lawyer for legal matters. Agreement Checker AI is not
                responsible for any decisions made based on this analysis.
              </p>
            </div>
          </div>
        </Card>

        <div className="flex flex-col sm:flex-row gap-4 mb-8">
          <Button size="lg" onClick={handleCopy} variant="outline" className="flex items-center justify-center">
            <Copy className="w-5 h-5 mr-2" />
            {copied ? 'Copied!' : 'Copy Summary'}
          </Button>
          <Button size="lg" onClick={handleDownload} variant="outline" className="flex items-center justify-center">
            <Download className="w-5 h-5 mr-2" />
            Download Report
          </Button>
          <Link to="/upload" className="flex-1">
            <Button size="lg" fullWidth className="flex items-center justify-center">
              <Upload className="w-5 h-5 mr-2" />
              Analyze Another Document
            </Button>
          </Link>
        </div>

        <div className="text-center text-sm text-gray-500">
          <p>
            Need help understanding something?{' '}
            <a href="#" className="text-blue-600 hover:underline">
              Contact our support team
            </a>
          </p>
        </div>
      </div>
    </div>
  );
};
